# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\speedometer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_spd(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(190, 190)
        self.techface = QtWidgets.QLabel(Form)
        self.techface.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.techface.setText("")
        self.techface.setPixmap(QtGui.QPixmap(".\\techface_spd.png"))
        self.techface.setObjectName("techface")
        self.needle = QtWidgets.QLabel(Form)
        self.needle.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.needle.setText("")
        self.needle.setPixmap(QtGui.QPixmap(".\\needle_spd.png"))
        self.needle.setObjectName("needle")
        self.indicator = QtWidgets.QLabel(Form)
        self.indicator.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.indicator.setText("")
        self.indicator.setPixmap(QtGui.QPixmap(".\\indicator_spd.png"))
        self.indicator.setObjectName("indicator")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
