project: ORL_optimizer
group: env
name: env_train
env_name: Ant-v3
chkpt_path: /home/james/sfu/ORL_optimizer/OtherModels/chkpt/ant_v3.pt
load_chkpt: true
save_chkpt_per: 500
sequence_num: 5
hidden_dim: 256
dones_cutoff:  0.6
num_epochs: 1000
eval_episodes: 20
batch_size: 2048
dynamics_lr: 0.001
rewards_lr: 0.001
dones_lr: 0.01
eval_seed: 42
train_seed: 0
eval_randomize: true
train_randomize: true