actor_bc_coef: 0.01
actor_learning_rate: 0.001
actor_ln: false
actor_n_hiddens: 3
batch_size: 1024
critic_bc_coef: 0.01
critic_learning_rate: 0.001
critic_ln: True
critic_n_hiddens: 3
dataset_name: hopper-medium-v2
eval_episodes: 5
eval_every: 20
eval_seed: 42
gamma: 0.99
group: james
hidden_dim: 256
name: rebrac-pytorch-augment
noise_clip: 0.5
normalize_q: True
normalize_reward: false
normalize_states: false
num_epochs: 2000
num_updates_on_epoch: 100
policy_freq: 2
policy_noise: 0.2
project: TORL
tau: 0.05
train_seed: 0
chkpt_path: MBORL/config/hopper/hopper_medium_v2_ar.pt
vae_chkpt_path: MBORL/config/hopper/hopper_medium_v2_vae.pt
use_gym_env: True   # no gym env
eval_step_limit: 1000
eval_total_steps: 5000
augment_step_limit: 1000
augment_total_steps: 5000
save_chkpt_path: MBORL/config/hopper/__tmp__/medium_v2_actor
save_chkpt_per: 10
sim_kappa: 0.01
replay_buffer_size: 50000
highreward_buffer_size: 50000
lowreward_buffer_size: 50000
d4rl_ratio: 0.7
myenv_ratio: 0.0
highreward_ratio: 0.0
lowreward_ratio: 0.3
elbo_cutoff: 36.0
elbo_threshold: 30.0
use_augment_data: True   # no data to replay buffer
augment_per: 10
augment_episode: 10
sensitivity_threshold: 0.05
reward_penalize: False