actor_bc_coef: 0.001
actor_learning_rate: 0.001
actor_ln: false
actor_n_hiddens: 3
batch_size: 1024
critic_bc_coef: 0.01
critic_learning_rate: 0.001
critic_ln: true
critic_n_hiddens: 3
dataset_name: halfcheetah-medium-v2
eval_episodes: 10
eval_every: 5
eval_seed: 42
gamma: 0.99
group: james
hidden_dim: 256
name: rebrac-pytorch-myenv
noise_clip: 0.5
normalize_q: true
normalize_reward: false
normalize_states: false
num_epochs: 1000
num_updates_on_epoch: 1000
policy_freq: 2
policy_noise: 0.2
project: TORL
tau: 0.05
train_seed: 0
chkpt_path: TORL/config/halfcheetah/halfcheetah_medium_v2_nar.pt
vae_chkpt_path: TORL/config/halfcheetah/halfcheetah_medium_v2_vae.pt
use_gym_env: true
eval_step_limit: 99999
save_chkpt_path: TORL/config/halfcheetah/__tmp__/medium_v2_actor
save_chkpt_per: 5
sim_kappa: 0.01
replay_buffer_size: 500000
