project: ORL_optimizer
group: env
name: env_train_offline
dataset_name: halfcheetah-medium-v2
chkpt_path_nar: TORL/config/halfcheetah_medium_v2_nar.pt
chkpt_path_ar: TORL/config/halfcheetah_medium_v2_ar_future_num980.pt
load_chkpt: false
save_chkpt_per: 500
sequence_num: 3
out_state_num: 1
hidden_dim: 128
future_num: 980
num_epochs: 100000
eval_episodes: 100
batch_size: 990
dynamics_lr: 0.001
dynamics_weight_decay: 1e-6
eval_seed: 42
train_seed:  0
eval_randomize: false
train_randomize: false
is_ar: true
holdout_per: 5
holdout_num: 5
holdout_randomize: true
