project: ORL_optimizer
group: env
name: env_train_offline
dataset_name: halfcheetah-medium-v2
chkpt_path: /home/james/sfu/ORL_optimizer/OtherModels/chkpt/halfcheetah_medium_v2.pt
load_chkpt: true
save_chkpt_per: 1000
sequence_num: 5
future_num: 900
out_state_num: 3
hidden_dim: 256
num_epochs: 3000
eval_episodes: 100
batch_size: 2
dynamics_lr: 0.001
eval_seed: 42
train_seed:  0
eval_randomize: true
train_randomize: true