project: ORL_optimizer
group: env
name: env_train_offline
dataset_name: halfcheetah-medium-v2
chkpt_path: /home/james/sfu/ORL_optimizer/OtherModels/chkpt/halfcheetah_medium_v2.pt
load_chkpt: true
save_chkpt_per: 500
sequence_num: 5
out_state_num: 1
hidden_dim: 128
future_num: 980
num_epochs: 50000
eval_episodes: 100
batch_size: 4
dynamics_lr: 0.001
dynamics_weight_decay: 1e-6
eval_seed: 42
train_seed:  0
eval_randomize: false
train_randomize: true